# This syncs the repository checkout into the live document root for morrisomondi.com (/home/tektxbzg/morris/)
deployment:
  tasks:
    - export DEPLOYPATH=/home/tektxbzg/morris/
    - /bin/mkdir -p $DEPLOYPATH
    - /usr/bin/rsync -rlptDv --exclude=".git" --exclude=".gitignore" --exclude=".cpanel.yml" --exclude=".env" ./ $DEPLOYPATH
